-- CTA Clicked Events Table
DROP TABLE IF EXISTS `cta_clicked`;
CREATE TABLE `cta_clicked` (
    `id` VARCHAR(255),
    `uuid_ts` TIMESTAMP,
    `context_request_ip` TEXT,
    `context_app_version` TEXT,
    `context_app_namespace` TEXT,
    `received_at` TIMESTAMP,
    `context_locale` TEXT,
    `channel` TEXT,
    `context_destination_id` TEXT,
    `user_id` TEXT,
    `cta_name` TEXT,
    `sent_at` TIMESTAMP,
    `context_page_referrer` TEXT,
    `context_source_id` TEXT,
    `context_traits_email` TEXT,
    `context_page_path` TEXT,
    `context_page_initial_referrer` TEXT,
    `cta_location` TEXT,
    `context_app_name` TEXT,
    `context_screen_inner_height` BIGINT,
    `original_timestamp` TIMESTAMP,
    `context_user_agent` TEXT,
    `context_page_title` TEXT,
    `context_library_version` TEXT,
    `context_ip` TEXT,
    `event` TEXT,
    `context_library_name` TEXT,
    `context_screen_inner_width` BIGINT,
    `context_screen_density` DECIMAL,
    `context_page_url` TEXT,
    `context_source_type` TEXT,
    `context_screen_width` BIGINT,
    `timestamp` TIMESTAMP,
    `context_destination_type` TEXT,
    `context_session_id` BIGINT,
    `anonymous_id` TEXT,
    `context_page_tab_url` TEXT,
    `event_text` TEXT,
    `context_screen_height` BIGINT,
    `context_page_referring_domain` TEXT,
    `context_page_initial_referring_domain` TEXT,
    `context_page_search` TEXT,
    `utm_source` TEXT,
    `context_campaign_source` TEXT,
    `gclid` TEXT,
    `context_session_start` BOOLEAN,
    `fbclid` TEXT,
    PRIMARY KEY (`id`)
);

-- CTA Hovered Events Table
DROP TABLE IF EXISTS `cta_hovered`;
CREATE TABLE `cta_hovered` (
    `id` VARCHAR(255),
    `cta_name` TEXT,
    `original_timestamp` TIMESTAMP,
    `context_page_title` TEXT,
    `context_page_url` TEXT,
    `context_destination_type` TEXT,
    `channel` TEXT,
    `context_traits_email` TEXT,
    `context_screen_inner_height` BIGINT,
    `sent_at` TIMESTAMP,
    `context_source_id` TEXT,
    `anonymous_id` TEXT,
    `context_source_type` TEXT,
    `context_screen_inner_width` BIGINT,
    `context_library_name` TEXT,
    `context_page_path` TEXT,
    `context_user_agent` TEXT,
    `context_page_tab_url` TEXT,
    `context_app_name` TEXT,
    `context_app_namespace` TEXT,
    `context_locale` TEXT,
    `user_id` TEXT,
    `context_screen_width` BIGINT,
    `context_page_initial_referrer` TEXT,
    `context_screen_density` DECIMAL,
    `timestamp` TIMESTAMP,
    `context_ip` TEXT,
    `context_library_version` TEXT,
    `context_screen_height` BIGINT,
    `context_session_id` BIGINT,
    `received_at` TIMESTAMP,
    `context_request_ip` TEXT,
    `context_app_version` TEXT,
    `uuid_ts` TIMESTAMP,
    `event_text` TEXT,
    `context_page_referrer` TEXT,
    `context_destination_id` TEXT,
    `event` TEXT,
    `context_page_initial_referring_domain` TEXT,
    `context_page_referring_domain` TEXT,
    `context_session_start` BOOLEAN,
    PRIMARY KEY (`id`)
);

-- Identifies Events Table
DROP TABLE IF EXISTS `identifies`;
CREATE TABLE `identifies` (
    `id` VARCHAR(255),
    `context_destination_id` TEXT,
    `user_id` TEXT,
    `received_at` TIMESTAMP,
    `context_library_name` TEXT,
    `context_traits_platform` TEXT,
    `context_destination_type` TEXT,
    `context_traits_address_city` TEXT,
    `context_ip` TEXT,
    `original_timestamp` TIMESTAMP,
    `context_source_type` TEXT,
    `context_source_id` TEXT,
    `context_request_ip` TEXT,
    `timestamp` TIMESTAMP,
    `context_traits_phone` TEXT,
    `context_traits_created_time` TEXT,
    `context_traits_city` TEXT,
    `context_traits_email` TEXT,
    `context_traits_adset_id` TEXT,
    `context_traits_campaign_id` TEXT,
    `uuid_ts` TIMESTAMP,
    `context_library_version` TEXT,
    `context_traits_ad_id` TEXT,
    `context_integration_name` TEXT,
    `context_traits_full_name` TEXT,
    `context_traits_phone_number` TEXT,
    `sent_at` TIMESTAMP,
    `context_traits_id` TEXT,
    `context_app_version` TEXT,
    `context_app_name` TEXT,
    `context_screen_inner_width` BIGINT,
    `context_page_tab_url` TEXT,
    `context_screen_inner_height` BIGINT,
    `context_page_path` TEXT,
    `context_app_namespace` TEXT,
    `channel` TEXT,
    `context_screen_width` BIGINT,
    `context_session_id` BIGINT,
    `context_screen_density` DECIMAL,
    `context_user_agent` TEXT,
    `anonymous_id` TEXT,
    `context_page_url` TEXT,
    `context_screen_height` BIGINT,
    `context_page_initial_referrer` TEXT,
    `context_locale` TEXT,
    `context_page_title` TEXT,
    `context_page_referrer` TEXT,
    PRIMARY KEY (`id`)
);

-- Pages Events Table
DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
    `id` VARCHAR(255),
    `path` TEXT,
    `title` TEXT,
    `context_locale` TEXT,
    `uuid_ts` TIMESTAMP,
    `context_library_version` TEXT,
    `referrer` TEXT,
    `received_at` TIMESTAMP,
    `context_page_url` TEXT,
    `context_ip` TEXT,
    `context_user_agent` TEXT,
    `context_page_tab_url` TEXT,
    `context_page_path` TEXT,
    `url` TEXT,
    `context_session_id` BIGINT,
    `initial_referrer` TEXT,
    `channel` TEXT,
    `context_screen_height` BIGINT,
    `context_app_namespace` TEXT,
    `context_app_name` TEXT,
    `context_traits_email` TEXT,
    `context_screen_inner_height` BIGINT,
    `anonymous_id` TEXT,
    `context_request_ip` TEXT,
    `context_screen_width` BIGINT,
    `context_session_start` BOOLEAN,
    `context_destination_id` TEXT,
    `context_destination_type` TEXT,
    `context_library_name` TEXT,
    `context_source_id` TEXT,
    `sent_at` TIMESTAMP,
    `context_page_title` TEXT,
    `original_timestamp` TIMESTAMP,
    `context_app_version` TEXT,
    `context_page_initial_referrer` TEXT,
    `user_id` TEXT,
    `context_screen_density` DECIMAL,
    `tab_url` TEXT,
    `context_source_type` TEXT,
    `context_screen_inner_width` BIGINT,
    `timestamp` TIMESTAMP,
    `context_page_referrer` TEXT,
    `context_page_initial_referring_domain` TEXT,
    `context_page_referring_domain` TEXT,
    `initial_referring_domain` TEXT,
    `referring_domain` TEXT,
    `context_page_search` TEXT,
    `search` TEXT,
    `fbclid` TEXT,
    `utm_source` TEXT,
    `context_campaign_source` TEXT,
    `gclid` TEXT,
    `utm_medium` TEXT,
    `utm_term` TEXT,
    `context_campaign_name` TEXT,
    `utm_content` TEXT,
    `context_campaign_id` TEXT,
    `utm_campaign` TEXT,
    `context_campaign_term` TEXT,
    `context_campaign_content` TEXT,
    `context_campaign_medium` TEXT,
    `context_tracking_plan_id` TEXT,
    `context_tracking_plan_version` BIGINT,
    PRIMARY KEY (`id`)
);

-- Tracks Events Table
DROP TABLE IF EXISTS `tracks`;
CREATE TABLE `tracks` (
    `id` VARCHAR(255),
    `anonymous_id` TEXT,
    `context_screen_inner_width` BIGINT,
    `context_screen_density` DECIMAL,
    `context_page_url` TEXT,
    `context_app_name` TEXT,
    `event` TEXT,
    `original_timestamp` TIMESTAMP,
    `user_id` TEXT,
    `context_session_id` BIGINT,
    `context_locale` TEXT,
    `sent_at` TIMESTAMP,
    `uuid_ts` TIMESTAMP,
    `context_ip` TEXT,
    `context_request_ip` TEXT,
    `context_traits_email` TEXT,
    `context_screen_inner_height` BIGINT,
    `context_screen_width` BIGINT,
    `context_app_namespace` TEXT,
    `context_destination_type` TEXT,
    `context_app_version` TEXT,
    `channel` TEXT,
    `context_destination_id` TEXT,
    `event_text` TEXT,
    `context_user_agent` TEXT,
    `context_source_type` TEXT,
    `context_page_referrer` TEXT,
    `timestamp` TIMESTAMP,
    `context_library_name` TEXT,
    `context_page_initial_referrer` TEXT,
    `context_screen_height` BIGINT,
    `context_source_id` TEXT,
    `context_page_tab_url` TEXT,
    `context_page_title` TEXT,
    `context_page_path` TEXT,
    `context_library_version` TEXT,
    `received_at` TIMESTAMP,
    `context_page_referring_domain` TEXT,
    `context_page_initial_referring_domain` TEXT,
    `context_session_start` BOOLEAN,
    `context_page_search` TEXT,
    `context_campaign_source` TEXT,
    PRIMARY KEY (`id`)
);
