-- CTA Clicked Events Table
-- DROP TABLE IF EXISTS `cta_clicked`;
CREATE TABLE `cta_clicked` (
    `id` VARCHAR(255),
    `uuid_ts` DATE,
    `context_request_ip` VARCHAR(255),
    `context_app_version` VARCHAR(255),
    `context_app_namespace` VARCHAR(255),
    `received_at` DATE,
    `context_locale` VARCHAR(255),
    `channel` VARCHAR(255),
    `context_destination_id` VARCHAR(255),
    `user_id` VARCHAR(255),
    `cta_name` VARCHAR(255),
    `sent_at` DATE,
    `context_page_referrer` VARCHAR(255),
    `context_source_id` VARCHAR(255),
    `context_traits_email` VARCHAR(255),
    `context_page_path` VARCHAR(255),
    `context_page_initial_referrer` VARCHAR(255),
    `cta_location` VARCHAR(255),
    `context_app_name` VARCHAR(255),
    `context_screen_inner_height` INT,
    `original_timestamp` DATE,
    `context_user_agent` VARCHAR(255),
    `context_page_title` VARCHAR(255),
    `context_library_version` VARCHAR(255),
    `context_ip` VARCHAR(255),
    `event` VARCHAR(255),
    `context_library_name` VARCHAR(255),
    `context_screen_inner_width` INT,
    `context_screen_density` DECIMAL,
    `context_page_url` VARCHAR(255),
    `context_source_type` VARCHAR(255),
    `context_screen_width` INT,
    `timestamp` DATE,
    `context_destination_type` VARCHAR(255),
    `context_session_id` INT,
    `anonymous_id` VARCHAR(255),
    `context_page_tab_url` VARCHAR(255),
    `event_text` VARCHAR(255),
    `context_screen_height` INT,
    `context_page_referring_domain` VARCHAR(255),
    `context_page_initial_referring_domain` VARCHAR(255),
    `context_page_search` VARCHAR(255),
    `utm_source` VARCHAR(255),
    `context_campaign_source` VARCHAR(255),
    `gclid` VARCHAR(255),
    `context_session_start` BOOLEAN,
    `fbclid` VARCHAR(255),
    PRIMARY KEY (`id`)
);

-- CTA Hovered Events Table
-- DROP TABLE IF EXISTS `cta_hovered`;
CREATE TABLE `cta_hovered` (
    `id` VARCHAR(255),
    `cta_name` VARCHAR(255),
    `original_timestamp` DATE,
    `context_page_title` VARCHAR(255),
    `context_page_url` VARCHAR(255),
    `context_destination_type` VARCHAR(255),
    `channel` VARCHAR(255),
    `context_traits_email` VARCHAR(255),
    `context_screen_inner_height` INT,
    `sent_at` DATE,
    `context_source_id` VARCHAR(255),
    `anonymous_id` VARCHAR(255),
    `context_source_type` VARCHAR(255),
    `context_screen_inner_width` INT,
    `context_library_name` VARCHAR(255),
    `context_page_path` VARCHAR(255),
    `context_user_agent` VARCHAR(255),
    `context_page_tab_url` VARCHAR(255),
    `context_app_name` VARCHAR(255),
    `context_app_namespace` VARCHAR(255),
    `context_locale` VARCHAR(255),
    `user_id` VARCHAR(255),
    `context_screen_width` INT,
    `context_page_initial_referrer` VARCHAR(255),
    `context_screen_density` DECIMAL,
    `timestamp` DATE,
    `context_ip` VARCHAR(255),
    `context_library_version` VARCHAR(255),
    `context_screen_height` INT,
    `context_session_id` INT,
    `received_at` DATE,
    `context_request_ip` VARCHAR(255),
    `context_app_version` VARCHAR(255),
    `uuid_ts` DATE,
    `event_text` VARCHAR(255),
    `context_page_referrer` VARCHAR(255),
    `context_destination_id` VARCHAR(255),
    `event` VARCHAR(255),
    `context_page_initial_referring_domain` VARCHAR(255),
    `context_page_referring_domain` VARCHAR(255),
    `context_session_start` BOOLEAN,
    PRIMARY KEY (`id`)
);

-- Identifies Events Table
-- DROP TABLE IF EXISTS `identifies`;
CREATE TABLE `identifies` (
    `id` VARCHAR(255),
    `context_destination_id` VARCHAR(255),
    `user_id` VARCHAR(255),
    `received_at` DATE,
    `context_library_name` VARCHAR(255),
    `context_traits_platform` VARCHAR(255),
    `context_destination_type` VARCHAR(255),
    `context_traits_address_city` VARCHAR(255),
    `context_ip` VARCHAR(255),
    `original_timestamp` DATE,
    `context_source_type` VARCHAR(255),
    `context_source_id` VARCHAR(255),
    `context_request_ip` VARCHAR(255),
    `timestamp` DATE,
    `context_traits_phone` VARCHAR(255),
    `context_traits_created_time` VARCHAR(255),
    `context_traits_city` VARCHAR(255),
    `context_traits_email` VARCHAR(255),
    `context_traits_adset_id` VARCHAR(255),
    `context_traits_campaign_id` VARCHAR(255),
    `uuid_ts` DATE,
    `context_library_version` VARCHAR(255),
    `context_traits_ad_id` VARCHAR(255),
    `context_integration_name` VARCHAR(255),
    `context_traits_full_name` VARCHAR(255),
    `context_traits_phone_number` VARCHAR(255),
    `sent_at` DATE,
    `context_traits_id` VARCHAR(255),
    `context_app_version` VARCHAR(255),
    `context_app_name` VARCHAR(255),
    `context_screen_inner_width` INT,
    `context_page_tab_url` VARCHAR(255),
    `context_screen_inner_height` INT,
    `context_page_path` VARCHAR(255),
    `context_app_namespace` VARCHAR(255),
    `channel` VARCHAR(255),
    `context_screen_width` INT,
    `context_session_id` INT,
    `context_screen_density` DECIMAL,
    `context_user_agent` VARCHAR(255),
    `anonymous_id` VARCHAR(255),
    `context_page_url` VARCHAR(255),
    `context_screen_height` INT,
    `context_page_initial_referrer` VARCHAR(255),
    `context_locale` VARCHAR(255),
    `context_page_title` VARCHAR(255),
    `context_page_referrer` VARCHAR(255),
    PRIMARY KEY (`id`)
);

-- Pages Events Table
-- DROP TABLE IF EXISTS `pages`;
CREATE TABLE `pages` (
    `id` VARCHAR(255),
    `path` VARCHAR(255),
    `title` VARCHAR(255),
    `context_locale` VARCHAR(255),
    `uuid_ts` DATE,
    `context_library_version` VARCHAR(255),
    `referrer` VARCHAR(255),
    `received_at` DATE,
    `context_page_url` VARCHAR(255),
    `context_ip` VARCHAR(255),
    `context_user_agent` VARCHAR(255),
    `context_page_tab_url` VARCHAR(255),
    `context_page_path` VARCHAR(255),
    `url` VARCHAR(255),
    `context_session_id` INT,
    `initial_referrer` VARCHAR(255),
    `channel` VARCHAR(255),
    `context_screen_height` INT,
    `context_app_namespace` VARCHAR(255),
    `context_app_name` VARCHAR(255),
    `context_traits_email` VARCHAR(255),
    `context_screen_inner_height` INT,
    `anonymous_id` VARCHAR(255),
    `context_request_ip` VARCHAR(255),
    `context_screen_width` INT,
    `context_session_start` BOOLEAN,
    `context_destination_id` VARCHAR(255),
    `context_destination_type` VARCHAR(255),
    `context_library_name` VARCHAR(255),
    `context_source_id` VARCHAR(255),
    `sent_at` DATE,
    `context_page_title` VARCHAR(255),
    `original_timestamp` DATE,
    `context_app_version` VARCHAR(255),
    `context_page_initial_referrer` VARCHAR(255),
    `user_id` VARCHAR(255),
    `context_screen_density` DECIMAL,
    `tab_url` VARCHAR(255),
    `context_source_type` VARCHAR(255),
    `context_screen_inner_width` INT,
    `timestamp` DATE,
    `context_page_referrer` VARCHAR(255),
    `context_page_initial_referring_domain` VARCHAR(255),
    `context_page_referring_domain` VARCHAR(255),
    `initial_referring_domain` VARCHAR(255),
    `referring_domain` VARCHAR(255),
    `context_page_search` VARCHAR(255),
    `search` VARCHAR(255),
    `fbclid` VARCHAR(255),
    `utm_source` VARCHAR(255),
    `context_campaign_source` VARCHAR(255),
    `gclid` VARCHAR(255),
    `utm_medium` VARCHAR(255),
    `utm_term` VARCHAR(255),
    `context_campaign_name` VARCHAR(255),
    `utm_content` VARCHAR(255),
    `context_campaign_id` VARCHAR(255),
    `utm_campaign` VARCHAR(255),
    `context_campaign_term` VARCHAR(255),
    `context_campaign_content` VARCHAR(255),
    `context_campaign_medium` VARCHAR(255),
    `context_tracking_plan_id` VARCHAR(255),
    `context_tracking_plan_version` INT,
    PRIMARY KEY (`id`)
);

-- Tracks Events Table
-- DROP TABLE IF EXISTS `tracks`;
CREATE TABLE `tracks` (
    `id` VARCHAR(255),
    `anonymous_id` VARCHAR(255),
    `context_screen_inner_width` INT,
    `context_screen_density` DECIMAL,
    `context_page_url` VARCHAR(255),
    `context_app_name` VARCHAR(255),
    `event` VARCHAR(255),
    `original_timestamp` DATE,
    `user_id` VARCHAR(255),
    `context_session_id` INT,
    `context_locale` VARCHAR(255),
    `sent_at` DATE,
    `uuid_ts` DATE,
    `context_ip` VARCHAR(255),
    `context_request_ip` VARCHAR(255),
    `context_traits_email` VARCHAR(255),
    `context_screen_inner_height` INT,
    `context_screen_width` INT,
    `context_app_namespace` VARCHAR(255),
    `context_destination_type` VARCHAR(255),
    `context_app_version` VARCHAR(255),
    `channel` VARCHAR(255),
    `context_destination_id` VARCHAR(255),
    `event_text` VARCHAR(255),
    `context_user_agent` VARCHAR(255),
    `context_source_type` VARCHAR(255),
    `context_page_referrer` VARCHAR(255),
    `timestamp` DATE,
    `context_library_name` VARCHAR(255),
    `context_page_initial_referrer` VARCHAR(255),
    `context_screen_height` INT,
    `context_source_id` VARCHAR(255),
    `context_page_tab_url` VARCHAR(255),
    `context_page_title` VARCHAR(255),
    `context_page_path` VARCHAR(255),
    `context_library_version` VARCHAR(255),
    `received_at` DATE,
    `context_page_referring_domain` VARCHAR(255),
    `context_page_initial_referring_domain` VARCHAR(255),
    `context_session_start` BOOLEAN,
    `context_page_search` VARCHAR(255),
    `context_campaign_source` VARCHAR(255),
    PRIMARY KEY (`id`)
);
